apiVersion: v2
name: ubuntu
description: A Helm chart for deploying Ubuntu with SSH access via NodePort (for development/testing)
icon: https://github.com/ubuntu.png
type: application
version: 0.1.2
appVersion: "24.04"
maintainers:
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - ubuntu
