{{- if .Values.ssh.enabled }}
{{- if or .Values.ssh.rootPassword .Values.ssh.authorizedKeys }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ubuntu.fullname" . }}-ssh
  labels:
    {{- include "ubuntu.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ssh.rootPassword }}
  root-password: {{ .Values.ssh.rootPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.ssh.authorizedKeys }}
  authorized-keys: {{ .Values.ssh.authorizedKeys | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
