apiVersion: v2
appVersion: "1.0"
description: A Helm chart for vLLM API inference server
home: https://www.phison.com/
icon: https://otterscale.com/phison-logo-p.svg
keywords:
- aidaptivcache
- inference
maintainers:
- email: shawn_tsai@phison.com
  name: Shawn
name: aidaptivcache-inference
type: application
version: 0.2.0