apiVersion: v2
name: aidaptivcache-inference
description: A Helm chart for vLLM API inference server
home: https://www.phison.com/
type: application
keywords:
  - aidaptivcache
  - inference
icon: https://otterscale.com/phison-logo-p.svg
version: 0.1.3
appVersion: "1.0"
maintainers:
- name: Shawn
  email: shawn_tsai@phison.com
