apiVersion: v2
name: otterscale
# renovate: github=otterscale/otterscale
appVersion: v0.6.3
version: 0.2.3
kubeVersion: ">= 1.30.0"
description: A Helm chart for OtterScale - Cloud infrastructure management platform
home: https://otterscale.github.io
icon: https://github.com/otterscale.png
sources:
  - https://github.com/otterscale/otterscale
maintainers:
  - name: terry
    email: terrywu25@gmail.com
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - otterscale
type: application
dependencies:
  - condition: keycloakx.enabled
    repository: "https://codecentric.github.io/helm-charts"
    name: keycloakx
    version: 7.1.5
