apiVersion: v2
name: otterscale
# renovate: github=otterscale/otterscale
appVersion: v0.7.0-alpha.3
version: 0.3.0-alpha.3
description: OtterScale - A unified platform for simplified compute, storage, and networking
home: https://otterscale.github.io
icon: https://github.com/otterscale.png
sources:
  - https://github.com/otterscale/otterscale
maintainers:
  - name: Yi-Lin Wu
    email: terrywu25@gmail.com
  - name: Chung-Hsuan Tsai
    email: paul_tsai@phison.com
keywords:
  - otterscale
type: application
dependencies:
  - condition: keycloakx.enabled
    repository: "https://codecentric.github.io/helm-charts"
    name: keycloakx
    version: 7.1.7
  - condition: valkey.enabled
    repository: "https://valkey.io/valkey-helm/"
    name: valkey
    version: 0.9.3
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x