apiVersion: v2
description: A Helm chart for OtterScale
keywords:
- kubernetes
- containers
- virtualization
- storage
- gpu-management
- maas
- juju
- ceph
- aidaptiv-cache
kubeVersion: '>= 1.30.0'
maintainers:
- email: terrywu25@gmail.com
  name: terry
name: otterscale
version: 0.2.0
dependencies:
- condition: keycloak.enabled
  repository: "oci://registry-1.docker.io/bitnamicharts"
  name: keycloak
  version: 25.2.5
