{{- if .Values.openfeature.sidecar.enabled }}
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlagSource
metadata:
  name: {{ .Values.openfeature.flagsource }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: openfeature
spec:
  sources:
    - source: {{ .Release.Namespace }}/otterscale-flags
      provider: kubernetes
{{- end }}
