{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "otterscale.fullname" . }}-gateway
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  selector:
    istio: istiod-ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      {{- toYaml .Values.istio.gateway.hosts | nindent 6 }}
    {{- if .Values.istio.tls.enabled }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
      {{- toYaml .Values.istio.gateway.hosts | nindent 6 }}
    tls:
      mode: SIMPLE
      credentialName: {{ include "otterscale.tls.secretName" . }}
    {{- end }}
{{- end }}
