{{- if and .Values.istio.tls.enabled (not .Values.istio.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.tls.secretName" . }}
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.istio.tls.crt | required "istio.tls.crt is required when TLS is enabled without existingSecret" }}
  tls.key: {{ .Values.istio.tls.key | required "istio.tls.key is required when TLS is enabled without existingSecret" }}
{{- end }}