{{- if and .Values.istio.enabled .Values.istio.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  selector:
    istio: istiod-ingress
  servers:
    {{- toYaml .Values.istio.gateway.servers | nindent 4 }}
{{- end }}
