{{- if .Values.istio.tls.enabled }}
{{- if or (eq .Values.istio.tls.crt "") (eq .Values.istio.tls.key "") }}
{{- fail "TLS is enabled but crt or key is not provided" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.fullname" . }}-tls-cert
  namespace: istio-system
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
data:
  tls.crt: {{ .Values.istio.tls.crt | b64enc }}
  tls.key: {{ .Values.istio.tls.key | b64enc }}
type: kubernetes.io/tls
{{- end }}