{{- if .Values.keycloakx.enabled -}}
{{- $secretName := printf "%s-keycloak-client-secret" (include "otterscale.fullname" .) -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if not $existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  client-secret: {{ include "otterscale.keycloak.clientSecret" . }}
{{- end -}}
{{- end }}
