{{- if .Values.keycloakx.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.keycloakx.postgresql.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.keycloakx.postgresql.cluster.instances }}
  imageName: {{ .Values.keycloakx.postgresql.cluster.imageName }}
  bootstrap:
    initdb:
      database: {{ .Values.keycloakx.postgresql.bootstrap.initdb.database }}
      owner: {{ .Values.keycloakx.postgresql.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.keycloakx.postgresql.bootstrap.initdb.secret.name }}
  storage:
    size: {{ .Values.keycloakx.postgresql.storage.size }}
    {{- if .Values.keycloakx.postgresql.storage.storageClass }}
    storageClass: {{ .Values.keycloakx.postgresql.storage.storageClass }}
    {{- end }}
{{- end }}
