{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otterscale-realm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  otterscale-realm.json: |
    {
      "realm": "otterscale",
      "displayName": "OtterScale",
      "enabled": true,
      "registrationAllowed": true,
      "rememberMe": true,
      "resetPasswordAllowed": true,
      "revokeRefreshToken": true,
      "refreshTokenMaxReuse": 2,
      "displayNameHtml": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/6/61/Phison-logo.svg\" alt=\"Phison\">",
      "loginTheme": "otterscale-theme",
      "clients": [
        {
          "enabled": true,
          "clientId": "otterscale",
          "clientAuthenticatorType": "client-secret",
          "secret": "Bp4peGsKk7kRCe6EOzchF5UNdXHW0xt5",
          "protocol": "openid-connect",
          "authorizationServicesEnabled": false,
          "directAccessGrantsEnabled": false,
          "publicClient": false,
          "serviceAccountsEnabled": false,
          "standardFlowEnabled": true,
          "frontchannelLogout": true,
          "redirectUris": [
            "http://192.168.196.48/*"
          ],
          "webOrigins": [
            "http://192.168.196.48"
          ],
          "attributes": {
            "frontchannel.logout.session.required": "true",
            "pkce.code.challenge.method": "S256"
          },
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "otterscale",
                "id.token.claim": "false",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "introspection.token.claim": "true"
              }
            },
            {
              "name": "client roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-client-role-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "multivalued": "true",
                "userinfo.token.claim": "false",
                "user.attribute": "foo",
                "id.token.claim": "true",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "claim.name": "resource_access.otterscale.roles",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ],
      "roles": {
        "client": {
          "otterscale": [
            {
              "name": "admin",
              "composite": false,
              "clientRole": true,
              "attributes": {}
            }
          ]
        }
      },
      "internationalizationEnabled": true,
      "supportedLocales": [
          "zh-TW",
          "en"
      ],
      "defaultLocale": "en",
      "authenticationFlows": [
        {
          "alias": "custom browser",
          "description": "Browser based authentication",
          "providerId": "basic-flow",
          "topLevel": true,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "auth-cookie",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 10,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-spnego",
              "authenticatorFlow": false,
              "requirement": "DISABLED",
              "priority": 20,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "identity-provider-redirector",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 25,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticatorFlow": true,
              "requirement": "ALTERNATIVE",
              "priority": 26,
              "autheticatorFlow": true,
              "flowAlias": "custom browser Organization",
              "userSetupAllowed": false
            },
            {
              "authenticatorFlow": true,
              "requirement": "ALTERNATIVE",
              "priority": 30,
              "autheticatorFlow": true,
              "flowAlias": "custom browser forms",
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "custom browser Browser - Conditional 2FA",
          "description": "Flow to determine if any 2FA is required for the authentication",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "conditional-user-configured",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 20,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticatorConfig": "custom browser browser-conditional-credential",
              "authenticator": "conditional-credential",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 30,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-otp-form",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 40,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "webauthn-authenticator",
              "authenticatorFlow": false,
              "requirement": "DISABLED",
              "priority": 50,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-recovery-authn-code-form",
              "authenticatorFlow": false,
              "requirement": "DISABLED",
              "priority": 51,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "custom browser Browser - Conditional Organization",
          "description": "Flow to determine if the organization identity-first login is to be used",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "conditional-user-configured",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 10,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "organization",
              "authenticatorFlow": false,
              "requirement": "ALTERNATIVE",
              "priority": 20,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "custom browser Organization",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticatorFlow": true,
              "requirement": "CONDITIONAL",
              "priority": 10,
              "autheticatorFlow": true,
              "flowAlias": "custom browser Browser - Conditional Organization",
              "userSetupAllowed": false
            }
          ]
        },
        {
          "alias": "custom browser forms",
          "description": "Username, password, otp and other auth forms.",
          "providerId": "basic-flow",
          "topLevel": false,
          "builtIn": false,
          "authenticationExecutions": [
            {
              "authenticator": "auth-username-form",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 10,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticator": "auth-password-form",
              "authenticatorFlow": false,
              "requirement": "REQUIRED",
              "priority": 20,
              "autheticatorFlow": false,
              "userSetupAllowed": false
            },
            {
              "authenticatorFlow": true,
              "requirement": "CONDITIONAL",
              "priority": 22,
              "autheticatorFlow": true,
              "flowAlias": "custom browser Browser - Conditional 2FA",
              "userSetupAllowed": false
            }
          ]
        }
      ],
      "authenticatorConfig": [
        {
          "alias": "custom browser browser-conditional-credential",
          "config": {
            "credentials": "webauthn-passwordless"
          }
        }
      ],
      "browserFlow": "custom browser",
      "attributes": {
        "darkMode": "true"
      }
    }
{{- end }}
