{{- if .Values.keycloakx.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakx.postgresql.cluster.name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.keycloakx.postgresql.auth.username | quote }}
  password: {{ .Values.keycloakx.postgresql.auth.password | quote }}
  host: {{ .Values.keycloakx.postgresql.cluster.name }}-rw
  port: "5432"
  dbname: {{ .Values.keycloakx.postgresql.auth.database | quote }}
{{- end }}
