{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-keycloak-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: admin
  password: Yv5A9LvGpexKFnEe9VK82ojDv668fpG2
{{- end }}
