{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.fullname" . }}-keycloak-admin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" "otterscale-keycloak-admin" "key" "KC_BOOTSTRAP_ADMIN_PASSWORD" "length" 10 "providedValues" (list "keycloakx.auth.adminPassword") "context" .) }}
{{- end }}
