{{- if .Values.keycloakx.enabled -}}

{{- $secretName := printf "%s-keycloak-admin" (include "otterscale.fullname" .) -}}
{{- $passwordKey := "KC_BOOTSTRAP_ADMIN_PASSWORD" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
data:
  {{ $passwordKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" $passwordKey "providedValues" (list "keycloakx.auth.adminPassword") "length" 10 "strong" false "failOnNew" false "context" $) }}
{{- end }}
