apiVersion: v1
kind: ConfigMap
metadata:
  name: otterscale-keycloak-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
    {{- include "otterscale.labels" . | nindent 4 }}
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
  JAVA_OPTS_APPEND: >-
    -XX:+UseContainerSupport
    -XX:MaxRAMPercentage=50.0
    -Djava.awt.headless=true
    -Djgroups.dns.query=otterscale-keycloakx-headless
