{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: otterscale-keycloak-admin
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
data:
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ include "common.secrets.passwords.manage" (dict "secret" "otterscale-keycloak-admin" "key" "KC_BOOTSTRAP_ADMIN_PASSWORD" "length" 10 "providedValues" (list "keycloakx.auth.adminPassword") "context" .) | b64enc | quote }}
{{- end }}
