{{- if .Values.keycloakx.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-otterscale-realm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  otterscale-realm.json: |
    {
      "realm": "otterscale",
      "enabled": true,
      "displayNameHtml": "<img src=\"https://upload.wikimedia.org/wikipedia/commons/6/61/Phison-logo.svg\" alt=\"Phison\">",
      "registrationAllowed": true,
      "rememberMe": true,
      "resetPasswordAllowed": true,
      "revokeRefreshToken": true,
      "refreshTokenMaxReuse": 2,
      "loginTheme": "otterscale-theme",
      "sslRequired": "none",
      "clients": [
        {
          "enabled": true,
          "clientId": "otterscale",
          "clientAuthenticatorType": "client-secret",
          "secret": "Bp4peGsKk7kRCe6EOzchF5UNdXHW0xt5",
          "protocol": "openid-connect",
          "authorizationServicesEnabled": false,
          "standardFlowEnabled": true,
          "directAccessGrantsEnabled": false,
          "serviceAccountsEnabled": false,
          "publicClient": false,
          "frontchannelLogout": true,
          "redirectUris": [
            "http://192.168.196.48/*"
          ],
          "webOrigins": [
            "http://192.168.196.48"
          ],
          "attributes": {
            "frontchannel.logout.session.required": "true",
            "pkce.code.challenge.method": "S256"
          },
          "protocolMappers": [
            {
              "name": "audience-mapper",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-audience-mapper",
              "consentRequired": false,
              "config": {
                "included.client.audience": "otterscale",
                "id.token.claim": "false",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "introspection.token.claim": "true"
              }
            },
            {
              "name": "client roles",
              "protocol": "openid-connect",
              "protocolMapper": "oidc-usermodel-client-role-mapper",
              "consentRequired": false,
              "config": {
                "introspection.token.claim": "true",
                "multivalued": "true",
                "userinfo.token.claim": "false",
                "user.attribute": "foo",
                "id.token.claim": "true",
                "lightweight.claim": "false",
                "access.token.claim": "true",
                "claim.name": "resource_access.otterscale.roles",
                "jsonType.label": "String"
              }
            }
          ]
        }
      ],
      "roles": {
        "client": {
          "otterscale": [
            {
              "name": "admin",
              "composite": false,
              "clientRole": true,
              "attributes": {}
            }
          ]
        }
      }
    }
{{- end }}
