apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.otterscaleWeb.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "otterscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "otterscale.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
    spec:
      containers:
        - name: otterscale-web
          image: "{{ tpl .Values.otterscaleWeb.image.repository . }}:{{ tpl .Values.otterscaleWeb.image.tag . | default .Chart.AppVersion}}"
          imagePullPolicy: "{{ .Values.otterscaleWeb.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- with .Values.otterscaleWeb.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "otterscale.fullname" . }}-web-env
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
