apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.otterscaleWeb.replicas }}
  selector:
    matchLabels:
      {{- include "otterscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "otterscale.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
      annotations:
        {{- if .Values.openfeature.sidecar.enabled }}
        openfeature.dev/enabled: "true"
        openfeature.dev/featureflagsource: {{ .Values.openfeature.flagsource }}
        {{- end }}
        {{- with .Values.otterscaleWeb.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.postgresql.enabled }}
      initContainers:
        {{- include "otterscale.postgresql.waitInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: otterscale-web
          image: "{{ tpl .Values.otterscaleWeb.image.repository . }}:{{ tpl .Values.otterscaleWeb.image.tag . | default .Chart.AppVersion}}"
          imagePullPolicy: "{{ .Values.otterscaleWeb.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- if .Values.postgresql.enabled }}
            - name: DATABASE_URL
              value: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password .Release.Name .Values.postgresql.auth.database | quote }}
            {{- end }}
            - name: NODE_ENV
              value: "development"
            - name: ORIGIN
              value: {{ .Values.otterscaleWeb.env.publicWebUrl | quote }}
            - name: PUBLIC_WEB_URL
              value: {{ .Values.otterscaleWeb.env.publicWebUrl | quote }}
            - name: PUBLIC_API_URL
              value: {{ if .Values.otterscaleWeb.env.publicApiUrl }}{{ .Values.otterscaleWeb.env.publicApiUrl | quote }}{{ else }}"http://{{ include "otterscale.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8299"{{ end }}
            - name: KEYCLOAK_REALM_URL
              value: {{ .Values.otterscaleWeb.env.keycloakRealmUrl | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.otterscaleWeb.env.keycloakClientID | quote }}
            - name: KEYCLOAK_CLIENT_SECRET
              value: {{ .Values.otterscaleWeb.env.keycloakClientSecret | quote }}
            {{- with .Values.otterscaleWeb.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.otterscaleWeb.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.otterscaleWeb.resources | nindent 12 }}
      {{- with include "otterscale.nodeSelector" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "otterscale.affinity" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "otterscale.tolerations" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
