{{- $cloudnativePg := index .Values.otterscaleWeb "cloudnative-pg" -}}
{{- if $cloudnativePg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $cloudnativePg.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
spec:
  instances: {{ $cloudnativePg.cluster.instances }}
  imageName: {{ $cloudnativePg.cluster.imageName }}
  bootstrap:
    initdb:
      database: {{ $cloudnativePg.bootstrap.initdb.database }}
      owner: {{ $cloudnativePg.bootstrap.initdb.owner }}
      secret:
        name: {{ $cloudnativePg.bootstrap.initdb.secret.name }}
  storage:
    size: {{ $cloudnativePg.storage.size }}
    {{- if $cloudnativePg.storage.storageClass }}
    storageClass: {{ $cloudnativePg.storage.storageClass }}
    {{- end }}
{{- end }}
