apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.otterscaleWeb.replicas }}
  selector:
    matchLabels:
      {{- include "otterscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "otterscale.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
      annotations:
        {{- with .Values.otterscaleWeb.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: otterscale-web
          image: "{{ tpl .Values.otterscaleWeb.image.repository . }}:{{ tpl .Values.otterscaleWeb.image.tag . | default .Chart.AppVersion}}"
          imagePullPolicy: "{{ .Values.otterscaleWeb.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- with .Values.otterscaleWeb.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.otterscaleWeb.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      {{- with include "otterscale.nodeSelector" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      nodeSelector:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "otterscale.affinity" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      affinity:
        {{- . | nindent 8 }}
      {{- end }}
      {{- with include "otterscale.tolerations" (dict "component" .Values.otterscaleWeb "global" .Values.global) }}
      tolerations:
        {{- . | nindent 8 }}
      {{- end }}
