apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otterscale.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.otterscale.replicas | default 1 }}
  selector:
    matchLabels:
      {{- include "otterscale.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "otterscale.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
        {{- if and .Values.istio.enabled .Values.istio.sidecarInjection.enabled }}
        sidecar.istio.io/inject: "true"
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/otterscale-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: otterscale
          image: "{{ tpl .Values.otterscale.image.repository . }}:{{ tpl .Values.otterscale.image.tag . | default .Chart.AppVersion}}"
          imagePullPolicy: "{{ .Values.otterscale.image.pullPolicy }}"
          command: ["/app/otterscale", "serve"]
          ports:
            - name: http
              containerPort: 8299
              protocol: TCP
          {{- with .Values.otterscale.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/app/otterscale.yaml
              subPath: otterscale.yaml
              readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
      volumes:
        - name: config
          configMap:
            name: {{ include "otterscale.fullname" . }}-config
