apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloakx.database.existingSecret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-db: {{ .Values.keycloakx.database.database | default "keycloak" | b64enc | quote }}
  postgres-user: {{ .Values.keycloakx.database.username | default "keycloak" | b64enc | quote }}
  postgres-password: {{ include "otterscale.postgres.password" . | b64enc | quote }}