{{- if and .Values.keycloakx.enabled .Values.keycloakx.database.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "otterscale.fullname" . }}-postgres-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - {{ .Values.keycloakx.database.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.keycloakx.database.persistence.size }}
  {{- if .Values.keycloakx.database.persistence.storageClassName }}
  storageClassName: {{ .Values.keycloakx.database.persistence.storageClassName }}
  {{- end }}
{{- end }}
