{{- if .Values.keycloakx.enabled -}}

{{- $secretName := .Values.keycloakx.database.existingSecret -}}
{{- $passwordKey := "postgres-password" -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  postgres-db: {{ .Values.keycloakx.database.database | default "keycloak" | b64enc | quote }}
  postgres-user: {{ .Values.keycloakx.database.username | default "keycloak" | b64enc | quote }}
  {{ $passwordKey }}: {{ include "common.secrets.passwords.manage" (dict "secret" $secretName "key" $passwordKey "providedValues" (list "keycloakx.database.password") "length" 10 "strong" false "failOnNew" false "context" $) }}
{{- end }}
