apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterscale.fullname" . }}-valkey
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "otterscale.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
data:
  valkey-password: {{ include "otterscale.valkey.password" . | b64enc | quote }}