apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "registry.fullname" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
    {{- with .Values.dockerRegistry.labels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.dockerRegistry.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "registry.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dockerRegistry.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "registry.labels" . | nindent 8 }}
        {{- with .Values.dockerRegistry.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.dockerRegistry.securityContext }}
      securityContext:
        {{- omit . "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: registry
          {{- with .Values.dockerRegistry.containerSecurityContext }}
          securityContext:
            {{- omit . "enabled" | toYaml | nindent 12 }}
          {{- end }}
          image: "{{ .Values.dockerRegistry.image.repository }}:{{ .Values.dockerRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.dockerRegistry.image.pullPolicy }}
          env:
            - name: REGISTRY_STORAGE
              value: {{ .Values.dockerRegistry.storage | quote }}
          {{- with .Values.dockerRegistry.extraEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.dockerRegistry.service.port }}
              protocol: TCP
            {{- if .Values.dockerRegistry.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.dockerRegistry.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- with .Values.dockerRegistry.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dockerRegistry.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dockerRegistry.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.dockerRegistry.persistence.enabled }}
            - name: registry-storage
              mountPath: /var/lib/registry 
            - name: config-volume
              mountPath: /etc/docker/registry 
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.dockerRegistry.persistence.enabled }}
        - name: registry-storage
          persistentVolumeClaim:
            {{- if .Values.dockerRegistry.persistence.existingClaim }}
            claimName: {{ .Values.dockerRegistry.persistence.existingClaim }}
            {{- else }}
            claimName: {{ include "registry.fullname" . }} 
            {{- end }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ include "registry.fullname" . }}-config
            items:
              - key: config.yml
                path: config.yml

      {{- with .Values.dockerRegistry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.dockerRegistry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.dockerRegistry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
