apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    otterscale.com/type: registry
    {{- include "registry.labels" . | nindent 4 }}
    {{- with .Values.dockerRegistry.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.dockerRegistry.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.dockerRegistry.service.type }}
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.dockerRegistry.service.type "NodePort") .Values.dockerRegistry.service.nodePort }}
      nodePort: {{ .Values.dockerRegistry.service.nodePort }}
      {{- end }}
    - port: 5001
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "registry.selectorLabels" . | nindent 4 }}
    {{- with .Values.dockerRegistry.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}