apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aidaptivcache-finetune.fullname" . }}-train-data
  labels:
    {{- include "aidaptivcache-finetune.labels" . | nindent 4 }}
data:
  QA_dataset_config.yaml: |
{{ .Values.trainDataConfig | indent 4 }}
