apiVersion: v1
kind: Service
metadata:
  name: aidaptivcache-exporter
  namespace: {{ .Values.global.namespace }}
  labels:
    app: aidaptivcache-exporter
spec:
  clusterIP: None
  selector:
    app: aidaptivcache-exporter
  ports:
  - name: http
    port: {{ .Values.exporter.containerPort }}
    targetPort: {{ .Values.exporter.containerPort }}
    protocol: TCP
